#spring.application.name=demo
server.port=${PORT:8080}

#db.url=jdbc:postgresql://db.prhowplexmxxtprjwhgb.supabase.co:5432/postgres?sslmode=require
db.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
db.user=postgres
db.password=postgres@123
db.driver=org.postgresql.Driver

